#!/bin/bash
echo hello world 
cd "$(dirname "${BASH_SOURCE[0]}")"

touch index.html
touch style.css
touch script.js

echo -e "<!DOCTYPE html>
<html>
<head>
<link rel='stylesheet' href='style.css'>
<script src='script.js'>
</script>
</head>
<body>
</body>
<html>" >> index.html

code style.css index.html script.js
open -a "Google Chrome" index.html 



killall Terminal
